per-directory signed environment file support

diff --git a/environ/kshrc.in b/environ/kshrc.in
--- a/environ/kshrc.in
+++ b/environ/kshrc.in
@@ -1,6 +1,6 @@
 ###########################################################################
 #
-#      Last update: 2020-06-02.21:07:08
+#      Last update: 2020-09-03.23:53:37
 #
 #  ATTENTION READER OF THIS FILE
 #
@@ -854,12 +854,88 @@ if __isksh ; then
             SHELLFILESTRING=shell,$HOST,$REMOTE_HOST,$$,$TTY,w$WINDOW,sty$STY
         fi
     fi
+
+    sign_pfk_environ() {
+        if [[ ! -f ${HOME}/.pfk_environ_key ]] ; then
+            echo no ${HOME}/.pfk_environ_key
+            return 1
+        fi
+        if [[ -f .pfk_environ ]] ; then
+            echo signing $PWD/.pfk_environ ...
+            grep -v '#pfk_sign' .pfk_environ > .pfk_environ.1
+            set -- `cat ${HOME}/.pfk_environ_key .pfk_environ.1 | sha256sum -`
+            echo '#pfk_sign' $1 >> .pfk_environ.1
+            mv .pfk_environ.1 .pfk_environ
+        else
+            echo no .pfk_environ in this directory
+        fi
+    }
+
+    verify_pfk_environ() {
+        envfile="$1"
+        if [[ ! -f "$envfile" ]] ; then
+            return 1
+        fi
+        if [[ ! -f ${HOME}/.pfk_environ_key ]] ; then
+            echo no ${HOME}/.pfk_environ_key
+            return 1
+        fi
+        set -- `( cat ${HOME}/.pfk_environ_key ; grep -v '#pfk_sign' "$envfile" ) | sha256sum -`
+        calculated=$1
+        infile=$( awk '/#pfk_sign/ { print $2} ' "$envfile" )
+        if [[ "x$infile" = "x$calculated" ]] ; then
+            return 0
+        fi
+        return 1
+    }
+
+    find_pfk_environ() {
+        OIFS="$IFS"
+        IFS="/"
+        set -- $PWD
+        IFS="$OIFS"
+        d=
+        for f in "$@" ; do
+            if [[ "x$f" != "x" ]] ; then
+                if [[ "x$d" = "x" ]] ; then
+                    d="/${f}"
+                else
+                    d="${d}/${f}"
+                fi
+                if [[ -f "${d}/.pfk_environ" ]] ; then
+                    if verify_pfk_environ "${d}/.pfk_environ" ; then
+                        echo "${d}/.pfk_environ"
+                        return 0
+                    else
+                        echo "${d}/.pfk_environ" failed signature check 1>&2
+                    fi
+                fi
+            fi
+        done
+        return 1
+    }
+
+    new_pfk_environ_file=
+    current_pfk_environ_file=
+
     cd() {
         if [[ $# -eq 0 ]] ; then
             command cd
         else
             command cd "$*"
         fi
+
+        new_pfk_environ_file=$(find_pfk_environ)
+        if [[ "x$new_pfk_environ_file" != "x$current_pfk_environ_file" ]] ; then
+            if [[ "x$current_pfk_environ_file" != "x" ]] ; then
+                . "$current_pfk_environ_file" leave
+            fi
+            if [[ "x$new_pfk_environ_file" != "x" ]] ; then
+                . "$new_pfk_environ_file" enter
+            fi
+            current_pfk_environ_file="$new_pfk_environ_file"
+        fi
+
         if [[ x$INSIDE_EMACS != x ]] ; then
             echo SHELL_CWD_BEGIN:$PWD:SHELL_CWD_END
         fi
